# Generated by Django 4.2.16 on 2024-10-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_userprofile_bio_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profilepictures/default.png', null=True, upload_to='profilepictures'),
        ),
    ]
