# Generated by Django 4.2.16 on 2024-11-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_wishlistitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
    ]
